name: Monitor

on:
  schedule:
    - cron: '*/15 * * * *'   # every 15 minutes
  workflow_dispatch: {}       # manual run

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing runs/index.json

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci || npm i
          npx playwright install --with-deps

      - name: Build
        run: npx tsc

      - name: Run monitor
        env:
          STORE_URL: ${{ secrets.STORE_URL }}
          PRODUCT_URL: ${{ secrets.PRODUCT_URL }}
          ADD_TO_CART_SELECTOR: ${{ secrets.ADD_TO_CART_SELECTOR }}
          CART_VERIFY_SELECTOR: ${{ secrets.CART_VERIFY_SELECTOR }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node dist/monitor.js

      - name: Persist run log
        if: always()
        run: |
          echo "=== Show current runs/index.json (after agent wrote) ==="
          test -f runs/index.json && cat runs/index.json || echo "runs/index.json missing"

          echo "=== Git status before commit ==="
          git status --porcelain

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Make sure we're on main and up to date
          git branch
          git pull --rebase origin main || true

          # Stage and commit if changed
          git add runs/index.json || true
          git diff --staged -- runs/index.json || true
          git commit -m "chore: persist monitor run [skip ci]" || echo "No changes to commit"

          # Push explicitly to main
          git push origin HEAD:main

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/**
