name: Monitor

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci || npm i
          npx playwright install --with-deps

      - name: Show env & versions
        run: |
          node -v
          npm -v
          npx tsc -v || true

      - name: Show repo tree (before build)
        run: |
          ls -la
          echo "---- root package.json ----"
          cat package.json
          echo "---- tsconfig.json ----"
          cat tsconfig.json || true
          echo "---- src tree ----"
          find src -maxdepth 2 -type f -print || true

      - name: Build TypeScript
        run: npx tsc

      - name: Show dist tree (after build)
        run: |
          echo "---- dist tree ----"
          find dist -maxdepth 2 -type f -print

      - name: Run monitor
        env:
          STORE_URL: ${{ secrets.STORE_URL }}
          PRODUCT_URL: ${{ secrets.PRODUCT_URL }}
          ADD_TO_CART_SELECTOR: ${{ secrets.ADD_TO_CART_SELECTOR }}
          CART_VERIFY_SELECTOR: ${{ secrets.CART_VERIFY_SELECTOR }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node dist/monitor.js

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/**
